src/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using skateparatodos.Models;

namespace skateparatodos.Controllers
{
    public class ComentariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComentariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comentarios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comentarios.Include(c => c.Doacao).Include(c => c.Usuario);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comentarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Doacao)
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // GET: Comentarios/Create
        public IActionResult Create()
        {
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao");
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email");
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DoacaoId,UsuarioId,Texto,Data")] Comentario comentario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comentario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", comentario.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", comentario.UsuarioId);
            return View(comentario);
        }

        // GET: Comentarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios.FindAsync(id);
            if (comentario == null)
            {
                return NotFound();
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", comentario.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", comentario.UsuarioId);
            return View(comentario);
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DoacaoId,UsuarioId,Texto,Data")] Comentario comentario)
        {
            if (id != comentario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comentario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComentarioExists(comentario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", comentario.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", comentario.UsuarioId);
            return View(comentario);
        }

        // POST: DoacoesItens/Doar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComentario(string Texto, int DoacaoId)
        {
            //if (DoacaoId == null)
            //{
            //    return NotFound();
            //}

            if (Texto == null || Texto.Length == 0)
            {
                return NotFound();
            }

            var doacao = await _context.Doacoes.FindAsync(DoacaoId);
            if (doacao == null)
            {
                return NotFound();
            }

            Usuario usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Email == User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (usuario == null)
            {
                return NotFound();
            }
            Comentario comentario = new Comentario();
            comentario.UsuarioId = usuario.Id;
            comentario.Usuario = usuario;
            comentario.DoacaoId = DoacaoId;
            comentario.Doacao = doacao;
            comentario.Texto = Texto;
            comentario.Data = DateTime.Now;

            if (ModelState.IsValid)
            {

                _context.Add(comentario);
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction("Details", "Doacoes", new { id = comentario.DoacaoId });
        }

        // GET: Comentarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Doacao)
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comentario = await _context.Comentarios.FindAsync(id);
            _context.Comentarios.Remove(comentario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComentarioExists(int id)
        {
            return _context.Comentarios.Any(e => e.Id == id);
        }
    }
}

src/Controllers/DoacoesItensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using skateparatodos.Models;

namespace skateparatodos.Controllers
{
    public class DoacoesItensController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DoacoesItensController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DoacoesItens
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DoacoesItens.Include(d => d.Doacao).Include(d => d.Usuario);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DoacoesItens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doacaoItem = await _context.DoacoesItens
                .Include(d => d.Doacao)
                .Include(d => d.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doacaoItem == null)
            {
                return NotFound();
            }

            return View(doacaoItem);
        }

        // GET: DoacoesItens/Create
        public IActionResult Create()
        {
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao");
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email");
            return View();
        }

        // POST: DoacoesItens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DoacaoId,Descricao,Peca,UsuarioId")] DoacaoItem doacaoItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doacaoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", doacaoItem.UsuarioId);
            return View(doacaoItem);
        }

        // GET: DoacoesItens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doacaoItem = await _context.DoacoesItens.FindAsync(id);
            if (doacaoItem == null)
            {
                return NotFound();
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", doacaoItem.UsuarioId);
            return View(doacaoItem);
        }

        // POST: DoacoesItens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DoacaoId,Descricao,Peca,UsuarioId")] DoacaoItem doacaoItem)
        {
            if (id != doacaoItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doacaoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoacaoItemExists(doacaoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", doacaoItem.UsuarioId);
            return View(doacaoItem);
        }


        // POST: DoacoesItens/Doar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Doar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doacaoItem = await _context.DoacoesItens.FindAsync(id);
            if (doacaoItem == null)
            {
                return NotFound();
            }

            doacaoItem.Usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Email == User.FindFirstValue(ClaimTypes.NameIdentifier));
            doacaoItem.UsuarioId = doacaoItem.Usuario.Id;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doacaoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoacaoItemExists(doacaoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                //return RedirectToAction(nameof(Index));
                //return View(doacaoItem.Doacao);
                //ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
                return RedirectToAction("Details","Doacoes", new { id = doacaoItem.DoacaoId });
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", doacaoItem.UsuarioId);
            return View(doacaoItem.Doacao);
        }
        public async Task<IActionResult> Cancelar(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doacaoItem = await _context.DoacoesItens.FindAsync(id);
            if (doacaoItem == null)
            {
                return NotFound();
            }

            doacaoItem.Usuario = null;
            doacaoItem.UsuarioId = null;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doacaoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoacaoItemExists(doacaoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                //return RedirectToAction(nameof(Index));
                //return View(doacaoItem.Doacao);
                //ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
                return RedirectToAction("Details","Doacoes", new { id = doacaoItem.DoacaoId });
            }
            ViewData["DoacaoId"] = new SelectList(_context.Doacoes, "Id", "Descricao", doacaoItem.DoacaoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Email", doacaoItem.UsuarioId);
            return View(doacaoItem.Doacao);
        }

        // GET: DoacoesItens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doacaoItem = await _context.DoacoesItens
                .Include(d => d.Doacao)
                .Include(d => d.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doacaoItem == null)
            {
                return NotFound();
            }

            return View(doacaoItem);
        }

        // POST: DoacoesItens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doacaoItem = await _context.DoacoesItens.FindAsync(id);
            _context.DoacoesItens.Remove(doacaoItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoacaoItemExists(int id)
        {
            return _context.DoacoesItens.Any(e => e.Id == id);
        }
    }
}

src/Views/Doacoes/Create.cshtml
@model skateparatodos.Models.Doacao

@{
    ViewData["Title"] = "Create";
}

<h1>Nova Doação</h1>

<!--<h4>Doação</h4>-->
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Doacoes/Delete.cshtml
@model skateparatodos.Models.Doacao

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doacao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Email)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Views/Doacoes/Details.cshtml
@using System.Security.Claims
@model skateparatodos.Models.Doacao

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Doação</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Email)
        </dd>
    </dl>
    <h4>Peças</h4>
    <dl class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Peça
                    </th>
                    <th>
                        Doador
                    </th>
                    <th>
                        Ações
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.DoacoesItens.OrderByDescending(c => c.Peca))
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Peca)
                        </td>
                        <td>
                            @if (item.Usuario != null)
                            {
                                @Html.DisplayFor(modelItem => item.Usuario.Nome)
                            }
                        </td>
                        <td>
                            @if (item.Usuario != null)
                            {
                                <form asp-action="Cancelar" asp-controller="DoacoesItens" asp-route-id="@item.Id">
                                    <input type="submit" value="Cancelar" class="btn btn-primary" />
                                </form>
                            }
                            else
                            {
                                <form asp-action="Doar" asp-controller="DoacoesItens" asp-route-id="@item.Id">
                                    <input type="submit" value="Doar" class="btn btn-primary" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </dl>
    <h4>Conversa</h4>
    <dl class="row">
        <form asp-action="CreateComentario" asp-controller="Comentarios">
            <input type="hidden" name="DoacaoId" value="@Model.Id" />
            <input type="text" name="Texto" class="form-control" />
            <input type="submit" value="Comentar" class="btn btn-primary" />
        </form>
    </dl>
    <dl class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Comentário
                    </th>
                    <th>
                        Nome
                    </th>
                    <th>
                        Data
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Comentarios.OrderByDescending(c => c.Data))
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Texto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Usuario.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Data)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </dl>
</div>
<div>
    <!--<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |-->
    <a asp-action="Index">Voltar para Doações</a>
</div>

src/Views/Doacoes/Edit.cshtml
@model skateparatodos.Models.Doacao

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Doacao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCriacao" class="control-label"></label>
                <p>@Html.DisplayFor(model => model.DataCriacao)</p>
                <span asp-validation-for="DataCriacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<StatusDoacao>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <p>@Html.DisplayFor(model => model.UsuarioId)</p>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Doacoes/Index.cshtml
@model IEnumerable<skateparatodos.Models.Doacao>

@{
    ViewData["Title"] = "Doações";
}

<h1>Doações</h1>

<p>
    <a asp-action="Create">Nova Doação</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <!--<th></th>-->
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Titulo)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCriacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Nome)
            </td>
            <!--
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
            -->
        </tr>
}
    </tbody>
</table>